name: Form to Firebase

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Firebase Admin SDKをインストール
      - name: Install Firebase Admin SDK
        run: npm install firebase-admin

      # Firebaseにデータをアップロード
      - name: Upload data to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          node <<EOF
          const fs = require('fs');
          const admin = require('firebase-admin');

          // Firebaseサービスアカウントの初期化
          const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);

          admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
            databaseURL: 'https://test-51ebc-default-rtdb.firebaseio.com/'
          });

          const db = admin.database();
          const ref = db.ref('Students');

          // JSONファイル (data.json) の読み込み
          const formData = JSON.parse(fs.readFileSync('./data.json', 'utf8'));

          // Firebaseにデータを保存
          ref.push(formData)
            .then(() => console.log('Data successfully uploaded to Firebase!'))
            .catch(error => console.error('Error uploading data to Firebase:', error));
          EOF
