name: Upload Student Data to Firebase

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Firebase Admin SDKをインストール
      - name: Install Firebase Admin SDK
        run: npm install firebase-admin

      # Firebaseにデータをアップロード
      - name: Upload data to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          node <<EOF
          const fs = require('fs');
          const admin = require('firebase-admin');

          // Firebaseサービスアカウントの初期化
          const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);

          admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
            databaseURL: 'https://test-51ebc-default-rtdb.firebaseio.com/'
          });

          const db = admin.database();

          // JSONファイル (data.json) の読み込み
          const dataFilePath = './data.json';
          if (!fs.existsSync(dataFilePath)) {
            throw new Error(`JSON file not found at path: ${dataFilePath}`);
          }

          const formData = JSON.parse(fs.readFileSync(dataFilePath, 'utf8'));

          // 必須フィールドの確認
          const requiredFields = ['studentId', 'name', 'attendanceNumber', 'department', 'year', 'courseId'];
          for (const field of requiredFields) {
            if (!formData[field]) {
              throw new Error(`Missing required field: ${field}`);
            }
          }

          // Firebase用のディレクトリパスを構築
          const studentNumber = formData.studentId; // 学籍番号
          const refPath = `Students/student_number/${studentNumber}`;

          console.log(`Saving data to Firebase at path: ${refPath}`);

          const ref = db.ref(refPath);

          // Firebaseにデータを保存
          ref.set(formData)
            .then(() => console.log(`Data successfully uploaded to Firebase at path: ${refPath}`))
            .catch(error => {
              console.error('Error uploading data to Firebase:', error);
              process.exit(1);
            });
          EOF
