name: Firebase に学生データをアップロード

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Firebase Admin SDK のインストール
      - name: Firebase Admin SDK のインストール
        run: npm install firebase-admin

      # スクリプトを実行
      - name: Firebase にデータをアップロード
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node upload.js
